name: Telemetry Annotation
description: Fetch the release details from the component
inputs:
  component:
    description: "Name of the component"
  date:
    description: "Release Published date"
    required: true
  version:
    description: "Release Version"
    required: true
  type:
    description: "Release Type"
    required: true
  tenantId:
    description: "TenantId"
    required: true
  urlProduction:
    description: "urlProduction"
    required: true
  urlStaging:
    description: "urlStaging"
    required: true    

runs:
  using: composite
  steps:

    - name: Checkout annotations repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        pip install requests

    - name: Send Release details to endpoints
      shell: bash
      env:
        component: ${{ inputs.component }}
        date: ${{ inputs.date }}
        version: ${{ inputs.version }}
        type: ${{ inputs.type }}
        tenantId: ${{ inputs.tenantId }}
        urlProduction: ${{ inputs.urlProduction }}
        urlStaging: ${{ inputs.urlStaging }}
      run: python3 ${{ github.action_path }}/TelemetryAnnotations/annotations.py
