name: Release Details

on:
  push:
    branches:
      - main

jobs:
  print_release_details:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      RELEASE_DATE: ${{ github.event.release.published_at }}
      RELEASE_COMPONENT: ${{ github.event.repository.name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
       
      - name: Print Release Details
        run: |
           echo "export RELEASE_TAG = ${{ github.event.release.tag_name }}" >> $GITHUB_ENV
           echo "export RELEASE_DATE = ${{ github.event.release.published_at }}" >> $GITHUB_ENV
           echo "export RELEASE_COMPONENT = ${{ github.event.repository.name }}" >> $GITHUB_ENV

      -  name: Set up Python
         uses: zattoo/testRelease@main
         with:
          component: ${{env.RELEASE_COMPONENT}}
          date: ${{env.RELEASE_DATE}}
          version: ${{env.RELEASE_TAG}}
          type: "Release"
          tenantId: 1
