name: Release Details

on:
  release:
    types: [published]

jobs:
  print_release_details:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      RELEASE_DATE: ${{ github.event.release.published_at }}
      RELEASE_COMPONENT: ${{ github.event.repository.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
       
      - name: Print Release Details
        run: |
           echo "export RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
           echo "export RELEASE_DATE=${{ github.event.release.published_at }}" >> $GITHUB_ENV
           echo "export RELEASE_COMPONENT=${{ github.event.repository.name }}" >> $GITHUB_ENV

      -  name: Set up Python
         uses: ./.github/actions/Telmetry-Annotation
         with:
          COMPONENT: ${{env.RELEASE_COMPONENT}}
          DATE: ${{env.RELEASE_DATE}}
          VERSION: ${{env.RELEASE_TAG}}
          TYPE: "Release"
          TENANT_ID: 1

